title: vicky-sol4nki
description: "Walkthroughs, writeups and guides!"
url: "https://vicky-sol4nki.github.io"
baseurl: ""

author:
  name: vicky-sol4nki
  github: https://github.com/vicky-sol4nki
  linkedin: https://linkedin.com/in/vickysolanki
  tryhackme: https://tryhackme.com/p/key101

markdown: kramdown
permalink: /:title/
paginate: 10
paginate_path: "/page/:num/"

plugins:
  - jekyll-paginate
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
